general {
    hide_cursor = true
}

background {
    monitor =
    color = rgb(111111)
}

input-field {
    monitor =
    size = 320, 54
    outline_thickness = 2
    dots_size = 0.22
    dots_spacing = 0.25
    fade_on_empty = false
    placeholder_text = <i>Password...</i>
    position = 0, 0
    halign = center
    valign = center
}
