#!/usr/bin/env bash
set -Eeuo pipefail

ACTION="${1:-apply}"
SOURCE_DIR="$REPO_ROOT/modules/gui/files"
DETECTOR="$REPO_ROOT/modules/gui/detect-packages.sh"
TARGET_DIR="$TARGET_HOME/.config/hypr"
GPU_CONFIG="$TARGET_DIR/gpu.lua"
UDEV_RULE_FILE="/etc/udev/rules.d/70-arch-postinstall-gpu-paths.rules"

plan() {
  cat <<PLAN
  - auto-detect all PCI GPUs before package installation
  - AMD/Intel: install Mesa userspace graphics driver
  - NVIDIA: install the current nvidia-open kernel-module stack + nvidia-utils
    (Turing/GTX 16xx/RTX or newer; old NVIDIA requires a manual legacy path)
  - hybrid AMD/Intel + NVIDIA installs drivers for BOTH GPUs
  - nvidia-prime is installed ONLY for hybrid AMD/Intel + NVIDIA systems
  - GPU primary policy: $GPU_PRIMARY
PLAN

  while IFS= read -r line; do
    printf '  - %s\n' "$line"
  done < <("$DETECTOR" primary)

  cat <<'PLAN'
  - when a primary GPU is explicit, create stable /dev/dri/arch-gpu-* udev symlinks
  - set AQ_DRM_DEVICES with the primary GPU first and other detected GPUs as fallbacks
  - install minimal Hyprland 0.55+ Lua config using Ghostty
  - no Waybar, launcher, notification daemon or wallpaper daemon
  - install hyprlock + hypridle configuration
  - SUPER+L locks the session
  - idle: lock at 5 min, display off at 5.5 min, suspend at 30 min
  - preserve each existing user config once as *.pre-arch-setup
  - no display manager is configured
  - launch from a local TTY with: start-hyprland
PLAN
}

install_user_config() {
  local name source target
  name="$1"
  source="$SOURCE_DIR/$name"
  target="$TARGET_DIR/$name"
  [[ -f "$source" ]] || { echo "Missing $source" >&2; exit 1; }

  if [[ -e "$target" && ! -e "${target}.pre-arch-setup" ]]; then
    sudo -u "$TARGET_USER" cp -a "$target" "${target}.pre-arch-setup"
  fi

  sudo install -m 644 -o "$TARGET_USER" -g "$TARGET_USER" "$source" "$target"
}

install_generated_gpu_config() {
  local devices="$1" tmp
  tmp="$(mktemp)"

  {
    printf '%s\n' '-- Generated by arch-postinstall.'
    printf '%s\n' "-- Primary GPU policy: $GPU_PRIMARY"
    if [[ -n "$devices" ]]; then
      printf 'hl.env("AQ_DRM_DEVICES", "%s")\n' "$devices"
    else
      printf '%s\n' '-- AQ_DRM_DEVICES intentionally left unset: auto policy on a multi-GPU system.'
      printf '%s\n' '-- Re-run with --gpu-primary nvidia|amd|intel for an explicit renderer.'
    fi
  } > "$tmp"

  if [[ -e "$GPU_CONFIG" && ! -e "${GPU_CONFIG}.pre-arch-setup" ]]; then
    sudo -u "$TARGET_USER" cp -a "$GPU_CONFIG" "${GPU_CONFIG}.pre-arch-setup"
  fi

  sudo install -m 644 -o "$TARGET_USER" -g "$TARGET_USER" "$tmp" "$GPU_CONFIG"
  rm -f "$tmp"
}

install_gpu_udev_rules() {
  local rules="$1" tmp
  [[ -n "$rules" ]] || {
    # Remove only a rule created by this installer when switching back to
    # topology-agnostic auto mode. Preserve a one-time backup first.
    if [[ -e "$UDEV_RULE_FILE" ]]; then
      [[ -e "${UDEV_RULE_FILE}.pre-arch-setup" ]] || sudo cp -a "$UDEV_RULE_FILE" "${UDEV_RULE_FILE}.pre-arch-setup"
      sudo rm -f "$UDEV_RULE_FILE"
      sudo udevadm control --reload
    fi
    return
  }

  tmp="$(mktemp)"
  printf '%s\n' "$rules" > "$tmp"

  if [[ -e "$UDEV_RULE_FILE" && ! -e "${UDEV_RULE_FILE}.pre-arch-setup" ]]; then
    sudo cp -a "$UDEV_RULE_FILE" "${UDEV_RULE_FILE}.pre-arch-setup"
  fi

  sudo install -m 644 "$tmp" "$UDEV_RULE_FILE"
  rm -f "$tmp"

  sudo udevadm control --reload
  sudo udevadm trigger --subsystem-match=drm || true
}

apply() {
  local devices rules
  devices="$("$DETECTOR" drm-devices)"
  rules="$("$DETECTOR" udev-rules)"

  sudo -u "$TARGET_USER" mkdir -p "$TARGET_DIR"

  # Hyprland 0.55+ prefers hyprland.lua. Preserve any pre-existing legacy
  # hyprland.conf once, but do not delete user data.
  if [[ -e "$TARGET_DIR/hyprland.conf" && ! -e "$TARGET_DIR/hyprland.conf.pre-arch-setup" ]]; then
    sudo -u "$TARGET_USER" cp -a       "$TARGET_DIR/hyprland.conf"       "$TARGET_DIR/hyprland.conf.pre-arch-setup"
  fi

  install_user_config hyprland.lua
  install_user_config hypridle.conf
  install_user_config hyprlock.conf
  install_generated_gpu_config "$devices"
  install_gpu_udev_rules "$rules"

  printf 'Minimal Hyprland configuration installed for %s.\n' "$TARGET_USER"
  if [[ -n "$devices" ]]; then
    printf 'AQ_DRM_DEVICES=%s\n' "$devices"
  else
    printf 'AQ_DRM_DEVICES left unset (multi-GPU auto policy).\n'
  fi
  printf 'Launch from a LOCAL TTY as that user with: start-hyprland\n'
  printf 'A reboot is recommended after installing/changing NVIDIA kernel modules.\n'
}

case "$ACTION" in
  plan) plan ;;
  apply) apply ;;
  *) echo "Unknown action: $ACTION" >&2; exit 2 ;;
esac
